[theme]
primaryColor = "#6366F1"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#111827"
textColor = "#F3F4F6"
font = "sans serif"
baseRadius = "0.75rem"

[server]
headless = true
enableStaticServing = true
maxMessageSize = 1024
maxUploadSize = 1024
runOnSave = false
port = 8501

[browser]
gatherUsageStats = false
